spring:
  application:
    name: GestorLDS

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:gestorlds;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console

  mvc:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:8000,http://localhost,http://127.0.0.1:3000"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600

server:
  port: 8080

logging:
  level:
    root: INFO
    com.gestorlds: DEBUG
    org.springframework.security: DEBUG

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# JWT Configuration
app:
  jwt:
    secret: "your-super-secret-jwt-key-change-this-in-production-at-least-256-bits-long-12345"
    expiration: 86400000

# Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs